databases:
  - name: liga-libre-db
    plan: free
    databaseName: liga_libre
    user: liga_user

services:
  - type: web
    name: liga-libre-api
    plan: free
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_TYPE
        value: PostgreSql
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: liga-libre-db
          property: connectionString
