name: Acceptance Tests

on:
  workflow_run:
    workflows: ["Commit Stage"]
    types: [completed]

jobs:
  acceptance-tests:
    if: >-
      github.event.workflow_run.conclusion == 'success' &&
      startsWith(github.event.workflow_run.head_branch, 'v')

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build
        shell: pwsh
        run: ./scripts/build.ps1

      - name: Acceptance Tests
        shell: pwsh
        run: dotnet test Tests/Test.Acceptance/Test.Acceptance.csproj --configuration Release --no-build --logger trx --results-directory TestResults/Acceptance

      - name: Integration Tests
        shell: pwsh
        run: dotnet test Tests/Test.Integration/Test.Integration.csproj --configuration Release --no-build --logger trx --results-directory TestResults/Integration
