name: Release

on:
  workflow_run:
    workflows: ["Acceptance Tests"]
    types: [completed]

jobs:
  deploy-production:
    if: false # TODO: Deploy to production
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
        run: echo "Production deploy not configured yet"
  